// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import globals from 'globals';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/*.d.ts',
      '**/.svelte-kit/**',
      // Emscripten output, generated by packages/cspice-wasm/scripts/build-cspice.sh.
      'packages/cspice-wasm/wasm/**',
      // Vendored, minified third-party Draco decoder.
      'apps/viewer/test-catalogs/draco/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...svelte.configs['flat/recommended'],
  {
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
  },
  {
    files: ['**/*.svelte', '**/*.svelte.ts'],
    languageOptions: {
      parserOptions: { parser: tseslint.parser },
    },
  },
  {
    rules: {
      // The codebase marks deliberately unused parameters, bindings and
      // type-level assertions with a leading underscore.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
        },
      ],
      // Off until the existing `any` sites get real types. As a warning it
      // printed 100+ lines on every run without stopping the count growing;
      // turn it back on as an error once the typing cleanup lands.
      '@typescript-eslint/no-explicit-any': 'off',
      // A key is only correct if it is unique, and a duplicate throws at
      // runtime (each_key_duplicate). Svelte 5 handles unkeyed lists fine, so
      // retrofitting keys onto every existing block is more risk than the rule
      // buys.
      'svelte/require-each-key': 'off',
      // Flags every Map/Set in a component or .svelte.ts module, including
      // function-local scratch maps, copy-then-reassign updates and
      // non-reactive listener registries — all of the sites it found here.
      'svelte/prefer-svelte-reactivity': 'off',
    },
  },
  {
    // Coefficient tables transcribed digit-for-digit from the published
    // theories. The extra digits round to the nearest double, which is the
    // value intended; trimming them would only make the tables harder to
    // check against the source.
    files: [
      'packages/core/src/trajectories/analytical/TASS17.ts',
      'packages/core/src/trajectories/analytical/Gust86.ts',
    ],
    rules: {
      'no-loss-of-precision': 'off',
    },
  },
);
