/**
 * Layer 1b — a planetary archive as oracle (issue #28, Phase 1).
 *
 * `spice-oracle.test.ts` pins cosmolabe's composition to CSPICE's own. That is
 * necessary but circular: if cosmolabe and our own use of CSPICE agree on a
 * wrong convention — which frame, which aberration correction, which body
 * shape, what "sub-observer point" means — every tier passes. This one checks
 * against geometry somebody else composed: the PDS Ring-Moon Systems Node's
 * archived Cassini ISS geometry (the tables behind OPUS), computed by `oops`.
 * Not an independent ephemeris — it reads the same SPICE kernels — but an
 * independent *composition*, which is where cosmolabe has actually broken.
 *
 * 514 rows: every ISS frame of 2004 DOY 183–185 (Saturn orbit insertion) whose
 * target has an ephemeris in the SCPSE kernel — Saturn 299, Titan 197, and 18
 * across Mimas, Enceladus, Tethys, Dione, Rhea and Iapetus. Only the columns
 * that are independent of the camera's field of view are used, so no CK.
 *
 * Measured, not assumed (Phase 0, with every bound set from the worst residual
 * and re-measurable by zeroing it):
 *
 *   - The archive's convention is SPICE's `LT+S` and **INTERCEPT** sub-points.
 *     `GeometryCalculator`'s default `NEAR POINT` is off by 2.6° (sub-observer)
 *     and 4.15° (sub-solar) of latitude on Saturn — the planetocentric vs
 *     planetographic gap on an oblate body — and `NONE` puts Saturn's sub-solar
 *     longitude 0.059° out. Both are mutation guards below.
 *   - The trajectory has to be the reconstruction. The committed
 *     `040629AP_SCPSE_04179_04185.bsp` is a pre-burn predict; against it the
 *     Saturn range is 509 km out and Titan's sub-observer longitude 0.32°. The
 *     RMS node used `040909R_SCPSE_01066_04199.bsp` (Saturn range to 0.45 km);
 *     `scripts/make-cassini-soi-recon-spk.mjs` subsets it to these three days.
 *   - What remains is small and mostly systematic, and is pinned as measured
 *     rather than explained away: Saturn's sub-observer longitude carries a
 *     constant offset (+0.007° σ 0.001° under `LT+S`, +0.005° under `LT`) that
 *     its sub-solar longitude does not and that does not vary with range or
 *     time, and Titan's sub-solar latitude a constant +0.0019°. Neither is a
 *     timing or light-time effect; a pole or aberration-convention difference
 *     inside oops would fit, and is not established. Planetographic latitude
 *     is checked on Saturn only: the moons' residuals (to 0.1°) come from
 *     oops' choice of radii, not from composition.
 *
 * Two tiers, each grouped by body so a failure names its symptom: the CSPICE
 * calls behind `GeometryCalculator`, and the renderer's own composition
 * (`absolutePositionOf` + `rotationAt` + `composeBodyToWorldQuat`) with light
 * time applied by the test. Each carries mutation guards that must fail.
 *
 * Fixture: `__fixtures__/pds-geometry-soi.json`, regenerated by
 * `scripts/generate-pds-geometry-fixture.mjs`. Archive values are 3-decimal,
 * so ±0.0005° of every angular bound is quantization.
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildUniverseFromCatalog, type BuiltScene } from './_harness/buildUniverse.js';
import { GeometryCalculator, type GeometryConfig } from '../geometry/GeometryCalculator.js';
import { composeBodyToWorldQuat, rotateVecByQuat, type Vec3 } from '../kinematics.js';
import type { SpiceInstance } from '../spice-injection.js';
import type { CatalogJson } from '../catalog/CatalogLoader.js';

// ── fixture ──────────────────────────────────────────────────────────────────

interface ArchiveRow {
  opusId: string;
  target: string;
  utcMid: string;
  observationId: string;
  subObserverLatPc: number;
  subObserverLatPg: number;
  subObserverLonW: number;
  subSolarLatPc: number;
  subSolarLatPg: number;
  subSolarLonW: number;
  distanceKm: number;
  phaseDeg: number;
}

const FIXTURE = join(__dirname, '__fixtures__/pds-geometry-soi.json');
if (!existsSync(FIXTURE)) {
  throw new Error(`${FIXTURE} is missing — regenerate it with \`node scripts/generate-pds-geometry-fixture.mjs\`.`);
}
const ROWS: ArchiveRow[] = JSON.parse(readFileSync(FIXTURE, 'utf8')).rows;

/** Rows grouped the way failures should read: Saturn and Titan each carry
 *  enough rows to stand alone; the rest are 1–9 rows per moon. */
const GROUPS: Record<string, string[]> = {
  Saturn: ['SATURN'],
  Titan: ['TITAN'],
  'Mid-size moons': ['MIMAS', 'ENCELADUS', 'TETHYS', 'DIONE', 'RHEA', 'IAPETUS'],
};

// ── tolerances (measured; see header) ───────────────────────────────────────

type Quantity =
  | 'distanceKm'
  | 'subObserverLonW'
  | 'subObserverLatPc'
  | 'subObserverLatPg'
  | 'subSolarLonW'
  | 'subSolarLatPc'
  | 'subSolarLatPg'
  | 'phaseDeg';

/** What a failure of each quantity points at. */
const SYMPTOM: Record<Quantity, string> = {
  distanceKm: 'SPK chain / trajectory',
  subObserverLonW: 'rotation model or observer direction',
  subObserverLatPc: 'pole orientation or frame chain',
  subObserverLatPg: 'body shape (radii)',
  subSolarLonW: 'rotation model or light-time',
  subSolarLatPc: 'pole orientation',
  subSolarLatPg: 'body shape (radii)',
  phaseDeg: 'Sun/observer geometry',
};

type Bounds = Partial<Record<Quantity, number>>;

/** GeometryCalculator (CSPICE `LT+S`, INTERCEPT) vs the archive. Each bound
 *  sits just above the measured worst residual, which follows it. */
const CALCULATOR_TOL: Record<string, Bounds> = {
  Saturn: {
    distanceKm: 0.5, // 0.446 km, at 0.09–1.8 Mkm
    subObserverLonW: 0.01, // 0.0096°: the constant +0.007° offset (see header)
    subObserverLatPc: 0.003, // 0.0024°
    subObserverLatPg: 0.003, // 0.0027°
    subSolarLonW: 0.003, // 0.0024°
    subSolarLatPc: 0.001, // 0.00087°
    subSolarLatPg: 0.001, // 0.00092°
    phaseDeg: 0.0045, // 0.0039°
  },
  Titan: {
    distanceKm: 6.5, // 6.2 km — the moon ephemeris, not Cassini's
    subObserverLonW: 0.008, // 0.0072°
    subObserverLatPc: 0.003, // 0.0024°
    subSolarLonW: 0.001, // 0.00062° — 0.0032° without stellar aberration
    subSolarLatPc: 0.0025, // 0.0020°: the constant +0.0019° offset (see header)
    phaseDeg: 0.0045, // 0.0040°
  },
  'Mid-size moons': {
    distanceKm: 20, // 19.6 km (Iapetus, 1.5 Mkm away)
    subObserverLonW: 0.003, // 0.0027°
    subObserverLatPc: 0.004, // 0.0038°
    subSolarLonW: 0.001, // 0.00078° — 0.0052° without stellar aberration
    subSolarLatPc: 0.004, // 0.0036°
    phaseDeg: 0.006, // 0.0058°
  },
};

// ── geometry under test ─────────────────────────────────────────────────────

type Geometry = Record<Quantity, number>;
const DEG = 180 / Math.PI;
const toWest = (eastDeg: number) => (((-eastDeg % 360) + 360) % 360);
const wrap180 = (d: number) => ((((d + 180) % 360) + 360) % 360) - 180;

/** Planetographic latitude of a body-fixed surface point: the latitude of the
 *  ellipsoid normal there. */
function planetographicLat(p: Vec3, radii: number[]): number {
  const n = [p[0] / radii[0] ** 2, p[1] / radii[1] ** 2, p[2] / radii[2] ** 2];
  return Math.atan2(n[2], Math.hypot(n[0], n[1])) * DEG;
}

type Abcorr = NonNullable<GeometryConfig['abcorr']>;
type Method = NonNullable<GeometryConfig['subPointMethod']>;

/** The archive's quantities through `GeometryCalculator`, plus planetographic
 *  latitudes from the same sub-points (which it does not report). */
function calculatorGeometry(spice: SpiceInstance, row: ArchiveRow, abcorr: Abcorr, method: Method): Geometry {
  const et = spice.str2et(row.utcMid);
  const naifId = spice.bodn2c(row.target)!;
  const bodyFrame = `IAU_${row.target}`;
  const g = new GeometryCalculator(spice).compute(
    {
      bodyName: row.target,
      bodyFrame,
      naifId,
      observerName: 'CASSINI',
      abcorr,
      subPointMethod: method,
      computeIllumination: false,
      computeOrbitalElements: false,
      computeEarthAngles: false,
      computeBetaAngle: false,
      computeRADec: false,
      computeLST: false,
    },
    et,
  );
  const radii = spice.bodvcd(naifId, 'RADII');
  const so = spice.subpnt(method, row.target, et, bodyFrame, abcorr, 'CASSINI');
  const ss = spice.subslr(method, row.target, et, bodyFrame, abcorr, 'CASSINI');
  return {
    distanceKm: g.range!,
    subObserverLonW: toWest(g.subSCLongitude!),
    subObserverLatPc: g.subSCLatitude!,
    subObserverLatPg: planetographicLat(so.point, radii),
    subSolarLonW: toWest(g.subSolarLongitude!),
    subSolarLatPc: g.subSolarLatitude!,
    subSolarLatPg: planetographicLat(ss.point, radii),
    phaseDeg: g.sunBodySCAngle!,
  };
}

/** Residual (ours − archive) per quantity; longitudes wrapped to ±180°. */
function residuals(ours: Geometry, row: ArchiveRow): Geometry {
  const out = {} as Geometry;
  for (const q of Object.keys(SYMPTOM) as Quantity[]) {
    const d = ours[q] - row[q];
    out[q] = q.endsWith('LonW') ? wrap180(d) : d;
  }
  return out;
}

interface Worst {
  value: number;
  row: ArchiveRow;
}

/** Worst |residual| per quantity across a group's rows. */
function worstByQuantity(
  rows: ArchiveRow[],
  geometry: (row: ArchiveRow) => Partial<Geometry>,
): Partial<Record<Quantity, Worst>> {
  const worst: Partial<Record<Quantity, Worst>> = {};
  for (const row of rows) {
    const ours = geometry(row);
    const res = residuals(ours as Geometry, row);
    for (const q of Object.keys(ours) as Quantity[]) {
      const v = Math.abs(res[q]);
      if (!Number.isFinite(v)) throw new Error(`${row.opusId} ${row.target} ${q}: non-finite residual`);
      if (!worst[q] || v > worst[q]!.value) worst[q] = { value: v, row };
    }
  }
  return worst;
}

function describeWorst(q: Quantity, w: Worst): string {
  return `${q} (${SYMPTOM[q]}): worst ${w.value.toPrecision(3)} at ${w.row.opusId} ${w.row.utcMid}`;
}

// ── scene ───────────────────────────────────────────────────────────────────

const RECON_KERNELS = ['naif0012.tls', 'pck00010.tpc', 'cassini/040909R_SCPSE_04183_04185_subset.bsp'];
const PREDICT_KERNELS = ['naif0012.tls', 'pck00010.tpc', 'cassini/040629AP_SCPSE_04179_04185.bsp'];

const moon = (name: string) => ({
  name,
  class: 'moon',
  center: 'Saturn',
  trajectoryFrame: 'J2000',
  trajectory: { type: 'Builtin', name },
  rotationModel: { type: 'Builtin' },
});

/** The Saturn system as `cassini-soi.json` declares it (#118: SPICE Builtin
 *  rotations), so the Universe tier exercises the shipped demo's composition
 *  rather than the regression scene's hand-copied Uniform models. */
const SOI_CATALOG = {
  name: 'Saturn SOI (PDS oracle)',
  defaultTime: '2004-07-01T02:48:00',
  items: [
    { name: 'Sun', class: 'star', trajectory: { type: 'FixedPoint', position: [0, 0, 0] } },
    {
      name: 'Saturn',
      class: 'planet',
      center: 'Sun',
      trajectory: { type: 'Builtin', name: 'Saturn' },
      rotationModel: { type: 'Builtin' },
      items: [
        ...['Mimas', 'Enceladus', 'Tethys', 'Dione', 'Rhea', 'Titan', 'Iapetus'].map(moon),
        {
          name: 'Cassini',
          class: 'spacecraft',
          center: 'Saturn',
          trajectoryFrame: 'J2000',
          trajectory: { type: 'Spice', target: 'CASSINI', center: 'SATURN' },
        },
      ],
    },
  ],
} as CatalogJson;

const build = (kernels: string[]) =>
  buildUniverseFromCatalog({ catalog: SOI_CATALOG, kernels, defaultTime: SOI_CATALOG.defaultTime! });

// ── GeometryCalculator vs archive ───────────────────────────────────────────

describe('PDS geometry oracle: GeometryCalculator (CSPICE LT+S, intercept sub-points)', () => {
  let scene: BuiltScene;

  beforeAll(async () => {
    scene = await build(RECON_KERNELS);
  }, 60_000);

  it('the fixture covers the SOI window it claims to', () => {
    expect(ROWS.length).toBe(514);
    const counted = Object.values(GROUPS).flat();
    expect(ROWS.every((r) => counted.includes(r.target))).toBe(true);
  });

  for (const [group, targets] of Object.entries(GROUPS)) {
    describe(group, () => {
      const rows = ROWS.filter((r) => targets.includes(r.target));
      let worst: Partial<Record<Quantity, Worst>>;

      beforeAll(() => {
        worst = worstByQuantity(rows, (row) =>
          calculatorGeometry(scene.spice!, row, 'LT+S', 'INTERCEPT/ELLIPSOID'),
        );
      });

      for (const [q, tol] of Object.entries(CALCULATOR_TOL[group]) as [Quantity, number][]) {
        it(`${q} within ${tol}${q === 'distanceKm' ? ' km' : '°'} over ${rows.length} rows`, () => {
          const w = worst[q]!;
          expect(w.value, describeWorst(q, w)).toBeLessThan(tol);
        });
      }
    });
  }

  // Guards on the guard (cf. viewpoint-offset.test.ts): each mutation is a
  // convention this tier exists to pin. If any of them also passed, the bounds
  // above would be too loose to tell the conventions apart.
  describe('rejects the wrong conventions', () => {
    const saturn = ROWS.filter((r) => r.target === 'SATURN');
    const titan = ROWS.filter((r) => r.target === 'TITAN');

    it('without light-time (abcorr NONE), Saturn sub-solar longitude leaves tolerance', () => {
      const w = worstByQuantity(saturn, (row) => {
        const g = calculatorGeometry(scene.spice!, row, 'NONE', 'INTERCEPT/ELLIPSOID');
        return { subSolarLonW: g.subSolarLonW };
      }).subSolarLonW!;
      // Measured 0.059°: Saturn turns ~0.0094°/s and light time is 0.3–6 s.
      expect(w.value, describeWorst('subSolarLonW', w)).toBeGreaterThan(10 * CALCULATOR_TOL.Saturn.subSolarLonW!);
    });

    it('without stellar aberration (abcorr LT), Titan sub-solar longitude leaves tolerance', () => {
      const w = worstByQuantity(titan, (row) => {
        const g = calculatorGeometry(scene.spice!, row, 'LT', 'INTERCEPT/ELLIPSOID');
        return { subSolarLonW: g.subSolarLonW };
      }).subSolarLonW!;
      // Measured 0.0032°, against 0.0006° with it.
      expect(w.value, describeWorst('subSolarLonW', w)).toBeGreaterThan(2 * CALCULATOR_TOL.Titan.subSolarLonW!);
    });

    it('with near-point sub-points (the calculator default), Saturn latitudes are degrees out', () => {
      const w = worstByQuantity(saturn, (row) => {
        const g = calculatorGeometry(scene.spice!, row, 'LT+S', 'NEAR POINT/ELLIPSOID');
        return { subObserverLatPc: g.subObserverLatPc, subSolarLatPc: g.subSolarLatPc };
      });
      // Measured 2.8° and 4.15°.
      expect(w.subObserverLatPc!.value).toBeGreaterThan(1);
      expect(w.subSolarLatPc!.value).toBeGreaterThan(1);
    });

    it('against the pre-burn predict SPK, Saturn range leaves tolerance', async () => {
      const predict = await build(PREDICT_KERNELS);
      const w = worstByQuantity(saturn, (row) => {
        const g = calculatorGeometry(predict.spice!, row, 'LT+S', 'INTERCEPT/ELLIPSOID');
        return { distanceKm: g.distanceKm };
      }).distanceKm!;
      // Measured 509 km — why the reconstruction subset exists.
      expect(w.value, describeWorst('distanceKm', w)).toBeGreaterThan(100 * CALCULATOR_TOL.Saturn.distanceKm!);
    }, 60_000);
  });
});

// ── Universe (the renderer's composition) vs archive ────────────────────────

/** Speed of light, km/s — CSPICE's `clight_c`. */
const C_KM_S = 299792.458;

/**
 * The archive's quantities from what the renderer consumes —
 * `absolutePositionOf` (the frame chain), `rotationAt` and
 * `composeBodyToWorldQuat` (the J2000 obliquity step) — with one-way light time
 * applied here, since the Universe is geometric. Stellar aberration is not
 * applied, so the bounds below are the `LT` residuals, not `LT+S`.
 *
 * This is the path the obliquity (23.44°) and moon-displacement (73 km)
 * regressions broke. `spice-oracle.test.ts` pins it to CSPICE at the mm level;
 * this pins the pair of them to somebody else's answer.
 */
function universeGeometry(
  scene: BuiltScene,
  row: ArchiveRow,
  mutation: { noLightTime?: boolean; noFrameStep?: boolean } = {},
): Partial<Geometry> {
  const { universe, spice } = scene;
  const et = spice!.str2et(row.utcMid);
  const name = row.target[0] + row.target.slice(1).toLowerCase();
  const body = universe.getBody(name)!;
  const sub = (a: number[], b: number[]): Vec3 => [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
  const norm = (v: number[]) => Math.hypot(v[0], v[1], v[2]);

  // Target as it was when the light Cassini sees left it.
  const observer = universe.absolutePositionOf('Cassini', et);
  let lt = 0;
  for (let i = 0; i < 3 && !mutation.noLightTime; i++) {
    lt = norm(sub(universe.absolutePositionOf(name, et - lt), observer)) / C_KM_S;
  }
  const etT = et - lt;
  const target = universe.absolutePositionOf(name, etT);
  // And the Sun as it was when the light that lit the target left it.
  let ltSun = 0;
  for (let i = 0; i < 3 && !mutation.noLightTime; i++) {
    ltSun = norm(sub(universe.absolutePositionOf('Sun', etT - ltSun), target)) / C_KM_S;
  }
  const sun = universe.absolutePositionOf('Sun', etT - ltSun);

  const toObserver = sub(observer, target);
  const toSun = sub(sun, target);
  const q = body.rotationAt(etT)!;
  // The mutation is the old viewpoint bug verbatim: conjugating `rotationAt`
  // and stopping at the model's own source frame (EquatorJ2000 here).
  const bodyToWorld = mutation.noFrameStep
    ? ([q[0], -q[1], -q[2], -q[3]] as [number, number, number, number])
    : composeBodyToWorldQuat(q, body.rotation!.sourceFrame, 'EclipticJ2000', etT);
  const worldToBody: [number, number, number, number] = [bodyToWorld[0], -bodyToWorld[1], -bodyToWorld[2], -bodyToWorld[3]];
  const latLon = (v: Vec3) => {
    const b = rotateVecByQuat(v, worldToBody);
    return { lat: Math.asin(b[2] / norm(b)) * DEG, lonW: toWest(Math.atan2(b[1], b[0]) * DEG) };
  };
  const so = latLon(toObserver);
  const ss = latLon(toSun);
  const cosPhase = (toObserver[0] * toSun[0] + toObserver[1] * toSun[1] + toObserver[2] * toSun[2]) / (norm(toObserver) * norm(toSun));
  return {
    distanceKm: norm(toObserver),
    subObserverLonW: so.lonW,
    subObserverLatPc: so.lat,
    subSolarLonW: ss.lonW,
    subSolarLatPc: ss.lat,
    phaseDeg: Math.acos(Math.min(1, Math.max(-1, cosPhase))) * DEG,
  };
}

/** Universe + light time vs the archive. Without stellar aberration the
 *  moons' sub-solar longitudes are looser than the calculator's, and Saturn's
 *  sub-observer longitude and every phase angle happen to be tighter. */
const UNIVERSE_TOL: Record<string, Bounds> = {
  Saturn: {
    distanceKm: 0.5, // 0.42 km
    subObserverLonW: 0.005, // 0.0045°
    subObserverLatPc: 0.003, // 0.0023°
    subSolarLonW: 0.003, // 0.0027°
    subSolarLatPc: 0.0015, // 0.0012°
    phaseDeg: 0.001, // 0.00067°
  },
  Titan: {
    distanceKm: 6.5, // 6.2 km
    subObserverLonW: 0.0045, // 0.0040°
    subObserverLatPc: 0.0035, // 0.0030°
    subSolarLonW: 0.0035, // 0.0032°
    subSolarLatPc: 0.0025, // 0.0020°
    phaseDeg: 0.001, // 0.00064°
  },
  'Mid-size moons': {
    distanceKm: 20, // 19.5 km
    subObserverLonW: 0.004, // 0.0035°
    subObserverLatPc: 0.004, // 0.0036°
    subSolarLonW: 0.0055, // 0.0052°
    subSolarLatPc: 0.004, // 0.0034°
    phaseDeg: 0.001, // 0.00049°
  },
};

describe('PDS geometry oracle: Universe composition (absolutePositionOf + rotationAt, light-time)', () => {
  let scene: BuiltScene;

  beforeAll(async () => {
    scene = await build(RECON_KERNELS);
  }, 60_000);

  it('uses SPICE rotations for every target, not the analytical fallback', () => {
    for (const name of ['Saturn', 'Titan', 'Mimas', 'Enceladus', 'Tethys', 'Dione', 'Rhea', 'Iapetus']) {
      expect(scene.universe.getBody(name)!.rotation?.constructor.name, name).toBe('SpiceRotation');
    }
  });

  for (const [group, targets] of Object.entries(GROUPS)) {
    describe(group, () => {
      const rows = ROWS.filter((r) => targets.includes(r.target));
      let worst: Partial<Record<Quantity, Worst>>;

      beforeAll(() => {
        worst = worstByQuantity(rows, (row) => universeGeometry(scene, row));
      });

      for (const [q, tol] of Object.entries(UNIVERSE_TOL[group]) as [Quantity, number][]) {
        it(`${q} within ${tol}${q === 'distanceKm' ? ' km' : '°'} over ${rows.length} rows`, () => {
          const w = worst[q]!;
          expect(w.value, describeWorst(q, w)).toBeLessThan(tol);
        });
      }
    });
  }

  describe('rejects the wrong compositions', () => {
    const saturn = ROWS.filter((r) => r.target === 'SATURN');

    it('without light time, Saturn sub-solar longitude leaves tolerance', () => {
      const w = worstByQuantity(saturn, (row) => ({
        subSolarLonW: universeGeometry(scene, row, { noLightTime: true }).subSolarLonW,
      })).subSolarLonW!;
      expect(w.value, describeWorst('subSolarLonW', w)).toBeGreaterThan(10 * UNIVERSE_TOL.Saturn.subSolarLonW!);
    });

    it('without the source→world frame step (the obliquity bug), Titan latitudes are degrees out', () => {
      // Titan's SPICE rotation is stated in J2000 (its trajectoryFrame), so
      // composing it into the ecliptic world needs the obliquity step. Saturn's
      // is not — it has no trajectoryFrame, so its rotation is already
      // ECLIPJ2000-sourced and this mutation would be a no-op there.
      expect(scene.universe.getBody('Titan')!.rotation!.sourceFrame).toBe('J2000');
      const titan = ROWS.filter((r) => r.target === 'TITAN');
      const w = worstByQuantity(titan, (row) => {
        const g = universeGeometry(scene, row, { noFrameStep: true });
        return { subObserverLatPc: g.subObserverLatPc, subSolarLatPc: g.subSolarLatPc };
      });
      expect(w.subObserverLatPc!.value, describeWorst('subObserverLatPc', w.subObserverLatPc!)).toBeGreaterThan(1);
      expect(w.subSolarLatPc!.value, describeWorst('subSolarLatPc', w.subSolarLatPc!)).toBeGreaterThan(1);
    });
  });
});
